declare module '*.scss';
declare module '*.png';
declare module '*.jpg';
declare module '*.svg';
declare module '*.gif';
declare module '*.webp';
declare module 'redux-actions';
declare module 'react-alert-template-basic';
declare module '*.mp3';
